# Generated by Django 3.2.5 on 2021-08-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='extra_pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weekly_pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
