# Generated by Django 3.2.5 on 2021-09-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210831_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
    ]
