# Generated by Django 3.2.5 on 2021-09-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210831_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_suspension',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated',
        ),
        migrations.AddField(
            model_name='customer',
            name='end_suspension',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='start_suspension',
            field=models.DateField(blank=True, null=True),
        ),
    ]
